//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbElements
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationContent
    {
        public ApplicationContent()
        {
            this.MessageAttachment = new HashSet<MessageAttachment>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Photo130 { get; set; }
        public string Photo604 { get; set; }
    
        public virtual ICollection<MessageAttachment> MessageAttachment { get; set; }
    }
}
