//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbElements
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.Message1 = new HashSet<Message>();
            this.MessageAttachment = new HashSet<MessageAttachment>();
        }
    
        public System.Guid Guid { get; set; }
        public long OwnerId { get; set; }
        public Nullable<long> Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ReadStateId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public bool IsContainsEmojiSmiles { get; set; }
        public bool IsImportant { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> ChatId { get; set; }
        public Nullable<int> UsersCount { get; set; }
        public Nullable<long> AdminId { get; set; }
        public Nullable<int> PhotoPreviewsId { get; set; }
        public Nullable<System.Guid> ParentGuid { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Message> Message1 { get; set; }
        public virtual Message Message2 { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<MessageAttachment> MessageAttachment { get; set; }
    }
}
