//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbElements
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageAttachment
    {
        public Nullable<System.Guid> MessageGuid { get; set; }
        public System.Guid Guid { get; set; }
        public Nullable<long> PhotoId { get; set; }
        public Nullable<long> VideoId { get; set; }
        public Nullable<long> AudioId { get; set; }
        public Nullable<long> DocumentId { get; set; }
        public Nullable<long> GraffitiId { get; set; }
        public Nullable<long> LinkId { get; set; }
        public Nullable<long> NoteId { get; set; }
        public Nullable<long> ApplicationContentId { get; set; }
        public Nullable<long> PollId { get; set; }
        public Nullable<long> PageId { get; set; }
        public Nullable<long> AlbumId { get; set; }
        public Nullable<long> StickerId { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual ApplicationContent ApplicationContent { get; set; }
        public virtual Audio Audio { get; set; }
        public virtual Document Document { get; set; }
        public virtual Graffiti Graffiti { get; set; }
        public virtual Link Link { get; set; }
        public virtual Message Message { get; set; }
        public virtual Note Note { get; set; }
        public virtual Photo Photo { get; set; }
        public virtual Poll Poll { get; set; }
        public virtual Sticker Sticker { get; set; }
        public virtual Video Video { get; set; }
    }
}
