//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbElements
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Album> Album { get; set; }
        public DbSet<ApplicationContent> ApplicationContent { get; set; }
        public DbSet<Audio> Audio { get; set; }
        public DbSet<AudioGenre> AudioGenre { get; set; }
        public DbSet<Document> Document { get; set; }
        public DbSet<Graffiti> Graffiti { get; set; }
        public DbSet<Link> Link { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<MessageAttachment> MessageAttachment { get; set; }
        public DbSet<Note> Note { get; set; }
        public DbSet<Photo> Photo { get; set; }
        public DbSet<PhotoPreviews> PhotoPreviews { get; set; }
        public DbSet<Poll> Poll { get; set; }
        public DbSet<PollAnswer> PollAnswer { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Sticker> Sticker { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Video> Video { get; set; }
    }
}
