//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbElements
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poll
    {
        public Poll()
        {
            this.MessageAttachment = new HashSet<MessageAttachment>();
            this.PollAnswer = new HashSet<PollAnswer>();
        }
    
        public long Id { get; set; }
        public string Question { get; set; }
        public System.DateTime Created { get; set; }
        public int Votes { get; set; }
        public Nullable<long> AnswerId { get; set; }
        public Nullable<bool> IsAnonymous { get; set; }
    
        public virtual ICollection<MessageAttachment> MessageAttachment { get; set; }
        public virtual ICollection<PollAnswer> PollAnswer { get; set; }
    }
}
