//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbElements
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public long Id { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> UserId { get; set; }
    }
}
