//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbElements
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public Video()
        {
            this.MessageAttachment = new HashSet<MessageAttachment>();
        }
    
        public long Id { get; set; }
        public Nullable<long> OwnerId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Link { get; set; }
        public string Photo130 { get; set; }
        public string Photo320 { get; set; }
        public string Photo640 { get; set; }
        public Nullable<int> CommentsCount { get; set; }
        public Nullable<int> ViewsCount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Player { get; set; }
        public Nullable<bool> Repeat { get; set; }
        public Nullable<long> AlbumId { get; set; }
        public string UploadUrl { get; set; }
        public string AccessKey { get; set; }
    
        public virtual ICollection<MessageAttachment> MessageAttachment { get; set; }
    }
}
